name: deploying to production
on: [push]

jobs:
    prod-check:
        if: ${{github.ref == 'refs/head/main'}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "deploying to production"
            - run: echo ${{github.ref}}