name: deploying to production
on: [push]

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
    # Print entire github context as JSON
    - name: Dump GitHub context
      run: echo '${{ toJson(github) }}'
    
    # Print job context
    - name: Dump job context
      run: echo '${{ toJson(job) }}'
    
    # Print matrix context
    - name: Dump matrix
      run: echo '${{ toJson(matrix) }}'