name: information about repository
on: [push]


jobs:
    info:
        runs-on: ubuntu-latest
        
        if: ${{contains(github.event.head_commit.message , '[skip ci]')}}
        steps:
            - name: Print info
              run: |
                 echo "Repo: $GITHUB_REPOSITORY"
                 echo "Branch: $GITHUB_REF_NAME"
                 echo "Action: $GITHUB_ACTOR"
                 echo "Url: $GITHUB_API_URL"